[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = ["python3 -m ensurepip", "python3 -m pip install -r backend/requirements.txt"]

[start]
cmd = "cd backend && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
